"""New migration

Revision ID: 271a8f6c579d
Revises: 83c291e4afab
Create Date: 2025-09-11 14:29:45.657256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '271a8f6c579d'
down_revision = '83c291e4afab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('measurement_type', sa.Enum('COUNTABLE', 'UNCOUNTABLE', name='measurementtype', native_enum=False), nullable=False))
    op.add_column('item', sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype', native_enum=False), nullable=False))
    op.alter_column('item', 'karat_default',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('item', 'ojrat_default',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('item', 'profit_default',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('item', 'tax_default',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    op.drop_column('item', 'is_active')
    op.drop_column('item', 'description')
    op.drop_column('item', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('type', postgresql.ENUM('COUNTABLE', 'UNCOUNTABLE', name='itemtype'), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.alter_column('item', 'tax_default',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('item', 'profit_default',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('item', 'ojrat_default',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('item', 'karat_default',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               nullable=False)
    op.drop_column('item', 'transaction_type')
    op.drop_column('item', 'measurement_type')
    # ### end Alembic commands ###
