"""New migration

Revision ID: 3e177b3bff1c
Revises: 77e3c01d4e15
Create Date: 2025-09-07 12:16:21.548934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e177b3bff1c'
down_revision = '77e3c01d4e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
