"""New migration

Revision ID: 4b067e59ad20
Revises: aab62df4cac5
Create Date: 2025-09-12 12:27:45.201955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b067e59ad20'
down_revision = 'aab62df4cac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('name_fa', sa.String(), nullable=False))
    op.add_column('permission', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('permission', 'name',
               existing_type=postgresql.ENUM('CONTACT_UPDATE_ALL', name='permissionname'),
               type_=sa.Enum('CONTACT_UPDATE_ALL', name='permissionname', native_enum=False),
               existing_nullable=False)
    op.create_unique_constraint(None, 'permission', ['name_fa'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.alter_column('permission', 'name',
               existing_type=sa.Enum('CONTACT_UPDATE_ALL', name='permissionname', native_enum=False),
               type_=postgresql.ENUM('CONTACT_UPDATE_ALL', name='permissionname'),
               existing_nullable=False)
    op.drop_column('permission', 'description')
    op.drop_column('permission', 'name_fa')
    # ### end Alembic commands ###
