"""New migration

Revision ID: 83c291e4afab
Revises: 3e177b3bff1c
Create Date: 2025-09-09 10:20:15.274789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c291e4afab'
down_revision = '3e177b3bff1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_bank_account', sa.Column('card_number', sa.String(), nullable=True))
    op.alter_column('saved_bank_account', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_bank_account_card_number'), 'saved_bank_account', ['card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_bank_account_card_number'), table_name='saved_bank_account')
    op.alter_column('saved_bank_account', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('saved_bank_account', 'card_number')
    # ### end Alembic commands ###
