"""New migration

Revision ID: aab62df4cac5
Revises: 271a8f6c579d
Create Date: 2025-09-11 21:53:05.330138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab62df4cac5'
down_revision = '271a8f6c579d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('item', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('inventory_column_name', sa.Enum('NEW_GOLD_JEWELRY_WEIGHT', 'USED_GOLD_WEIGHT', 'SILVER_BAR_WEIGHT', 'GOLD_COIN_COUNT', name='inventorycolumnname', native_enum=False), nullable=False))
    op.add_column('item', sa.Column('display_name_fa', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'item', ['inventory_column_name'])
    op.create_unique_constraint(None, 'item', ['display_name_fa'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'display_name_fa')
    op.drop_column('item', 'inventory_column_name')
    op.drop_column('item', 'is_active')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
